[package]
name = "focuslock"
version = "1.0.0"
description = "FocusLock - Focus Session Management Application"
authors = ["FocusLock Team"]
license = "MIT"
repository = ""
default-run = "focuslock"
edition = "2021"
rust-version = "1.80"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "2", features = ["tray-icon", "image-ico", "image-png"] }
tauri-plugin-shell = "2"
